import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import FlickeringGrid from "@/components/magicui/flickering-grid";

export function FlickeringGridDemo() {
  return (
    <div className="absolute inset-0 z-0 w-full h-full bg-gray-900 overflow-hidden">
      <FlickeringGrid
        className="absolute inset-0 w-full h-full"
        squareSize={4}
        gridGap={6}
        color="#000000FF"
        maxOpacity={0.5}
        flickerChance={0.1}
      />
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative bg-gray-900`}>
        <div className="relative z-10">
          <Navbar />
        </div>
        <div className="relative z-10">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
